### ISSUE TITLE
您好，请问为啥“立即下载”这几个字没显示出来

### ISSUE THREAD

**Issue by ohyessir** [r00tSe7en/Fake-flash.cn#2]

**Comment by r00tSe7en** [comment]
> _没有提供描述。_

我这边测试是正常的，你那边是否为国外网络，可以看一下那个在线预览界面是不是正常的

**Comment by ohyessir** [comment]
可以了，不好意思唐突了，没过脑子就提问了。。。。立即下载那里后面缺少一个 style="display:block;" 已经解决了，不好意思麻烦了

**Comment by r00tSe7en** [comment]
> 可以了，不好意思唐突了，没过脑子就提问了。。。。立即下载那里后面缺少一个 style="display:block;" 已经解决了，不好意思麻烦了

好的，官方的js好像有更新内容，前些天用也遇到了点问题

**Comment by wgetnz** [comment]
官方js更新了，不能用了

**Comment by ohyessir** [comment]
好滴


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r00tSe7en/Fake-flash.cn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 上午9:48
收件人:&nbsp;"r00tSe7en/Fake-flash.cn"<Fake-flash.cn@noreply.github.com&gt;;
抄送:&nbsp;"-"<857119476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [r00tSe7en/Fake-flash.cn] 您好，请问为啥“立即下载”这几个字没显示出来 (#2)





 
官方js更新了，不能用了
